name: scrcpy-buddy
version: '1.0.0'
summary: GUI wrapper for scrcpy
description: |
  A simple, clean, minimalist GUI wrapper for scrcpy (https://github.com/Genymobile/scrcpy).
grade: stable
base: core24
confinement: classic

apps:
  scrcpy-buddy:
    command: scrcpy_buddy
    environment:
      PATH: /usr/local/bin:/usr/bin:/bin:$PATH
      # GTK/GNOME settings for Flutter
      GTK_USE_PORTAL: 1
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS
    slots:
      - dbus-scrcpy-buddy

slots:
  dbus-scrcpy-buddy:
    interface: dbus
    bus: session
    name: dev.codertainment.scrcpy_buddy

parts:
  scrcpy-buddy:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - pkg-config
      - libgtk-3-dev
      - libglib2.0-dev
      - libgdk-pixbuf2.0-dev
      - libcairo2-dev
      - libpango1.0-dev
      - libayatana-appindicator3-dev  # For tray_manager
    stage-packages:
      # Add GTK dependencies since we removed gnome extension
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libcairo2
      - libpango-1.0-0
      - libatk1.0-0
      - libayatana-appindicator3-1    # For tray_manager
    organize:
      assets/icon_light_256.png: meta/gui/icon_light.png
