# This one doesn't work x_x

name: scrcpy-buddy
version: '1.0.0'
summary: GUI wrapper for scrcpy
description: |
  A simple, clean, minimalist GUI wrapper for scrcpy (https://github.com/Genymobile/scrcpy).
grade: stable
base: core24
confinement: strict

apps:
  adb:
    command: usr/bin/adb
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/android:${LD_LIBRARY_PATH}
    plugs:
      - adb-support
      - network
      - network-bind
      - raw-usb

  scrcpy-buddy:
    command: scrcpy_buddy
    extensions: [gnome]
    environment:
      LD_LIBRARY_PATH: ${SNAP}/scrcpy-runtime/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/android:${LD_LIBRARY_PATH}
      PATH: ${SNAP}/scrcpy-runtime/usr/local/bin:${PATH}

    plugs:
      - scrcpy-runtime-2404
      # For running the Android Debug Bridge (adb) and
      # connecting the Android devices over USB or TCP/IP.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/connection.md
      - adb-support
      - network
      - network-bind
      - raw-usb

      # For scrcpy audio forwarding functionality.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/audio.md
      - alsa
      - audio-playback
      - pulseaudio

      # For scrcpy v4l2 emulation support.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/v4l2.md
      - camera

      # For scrcpy video & audio recording support.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/recording.md
      - home
      - removable-media

      # For scrcpy gamepad simulation support.
      # https://github.com/Genymobile/scrcpy/blob/master/doc/gamepad.md
      - joystick

      # Legacy desktop support.
      # https://github.com/canonical/snapd/blob/master/interfaces/builtin/unity7.go
      - unity7
    slots:
      - dbus-scrcpy-buddy

slots:
  dbus-scrcpy-buddy:
    interface: dbus
    bus: session
    name: dev.codertainment.scrcpy_buddy

plugs:
  scrcpy-runtime-2404:
    interface: content
    content: scrcpy-runtime-2404
    target: $SNAP/scrcpy-runtime
    default-provider: scrcpy-runtime-2404

parts:
  adb:
    plugin: nil
    stage-packages:
      - adb
      - android-libbase
      - android-libboringssl
      - android-libcutils
      - android-liblog
      - android-libziparchive
      - libbrotli1
      - libcap2
      - liblz4-1
      - libprotobuf32t64
      - libudev1
      - libusb-1.0-0
      - libzstd1

  lp-bug-2016358-workaround:
    plugin: nil
    override-prime: |
      craftctl default
      mkdir -p "${CRAFT_PRIME}/scrcpy-runtime"

  scrcpy-buddy:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libayatana-appindicator3-dev  # For tray_manager
    stage-packages:
      - libayatana-appindicator3-1    # For tray_manager
    organize:
      assets/icon_light_256.png: meta/gui/icon_light.png
